language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t tri/multi-client ./client 
  - docker build -t tri/multi-nginx ./nginx 
  - docker build -t tri/multi-server ./server 
  - docker build -t tri/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push tri/multi-client
  - docker push tri/multi-nginx 
  - docker push tri/multi-server
  - docker push tri/multi-worker